### PR TITLE
Print that the job is starting.

### PR DESCRIPTION
**Pull request by Mariatta**

### CODE REVIEW

**Comment by njsmith** [comment]
Do we want to put in any countermeasures against stdout buffering, just in case?

**Comment by Mariatta** [comment]
ok, so use the `-u` option in Procfile?

**Comment by njsmith** [comment]
That's a good simple way yeah

**Comment by Mariatta** [comment]
What would be a better way? 😬

**Comment by njsmith** [comment]
I think all the ways I know of are:

- pass `-u` on the command line
- set `PYTHONUNBUFFERED=1` in the environment
- (py37+ only) call `sys.stdout.reconfigure(line_buffering=True)`
- weird awkward hacks that have a similar effect and work on earlier versions but are weird awkward hacks

They're all kind of ... just fine? I don't think there's any major reason to prefer one over another.

**Comment by Mariatta** [comment]
Any harm in doing all of them? 😛
I've done all below
✅ added sys.stdout.reconfigure(line_buffering=True)
✅ set the `PYTHONUNBUFFERED` environment (in Heroku)
✅ add `-u` in the Procfile

**Comment by njsmith** [comment]
belt AND suspenders

AND umm I dunno glue or something?

**Comment by njsmith** [comment]
(I'm pretty sure they are all literally exactly equivalent, so no, no harm in doing all of them :-))

**Comment by njsmith** [comment]
anyway LGTM

looks like we're double-testing PRs from branches in the main repo, which I think there's some way to disable but is mostly harmless, just slows down travis slightly

**Comment by njsmith** [comment]
Ohand we don't even have any tests anyway :-) I guess I don't need to wait for the tests to pass then...

**Pull request merged**
